#!/usr/bin/env python3
"""
Post review findings as pending GitHub PR review comments.

Parses a review markdown file generated by review-before-pr, extracts findings
with file paths and line numbers, and creates a PENDING review on the PR via
the GitHub CLI (gh). Comments are not submitted — the user reviews and submits
them manually on GitHub.

Usage:
    python3 scripts/post_comments.py .review/review-branch.md [--pr 42] [--all] [--signature "text"]

Requirements:
    - gh CLI installed and authenticated
    - Current directory inside a git repo with a GitHub remote
"""

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


SIGNATURE = "\n\n---\n🔍 *Posted by [review-before-pr](https://github.com/amanblog/review-before-pr) — AI-assisted review*"


@dataclass
class Finding:
    """A single review finding extracted from the markdown."""
    number: int
    title: str
    priority: str  # Critical, High, Medium
    file_path: str
    line: Optional[int]
    body: str  # full markdown body of the finding (issue + suggestion)


@dataclass
class PRInfo:
    """GitHub PR metadata."""
    number: int
    url: str
    owner: str
    repo: str
    head_sha: str


def run_gh(args: List[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a gh CLI command and return the result."""
    cmd = ["gh"] + args
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=check)
    except FileNotFoundError:
        print("Error: 'gh' CLI not found. Install it: https://cli.github.com/", file=sys.stderr)
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"Error running gh: {e.stderr.strip()}", file=sys.stderr)
        sys.exit(1)


def detect_pr(pr_number: Optional[int] = None) -> Optional[PRInfo]:
    """Detect the PR for the current branch using gh CLI."""
    if pr_number:
        # Fetch specific PR
        result = run_gh([
            "pr", "view", str(pr_number),
            "--json", "number,url,headRepository,headRefOid,headRepositoryOwner"
        ], check=False)
    else:
        # Try to find PR for current branch
        result = run_gh([
            "pr", "view",
            "--json", "number,url,headRepository,headRefOid,headRepositoryOwner"
        ], check=False)

    if result.returncode != 0:
        return None

    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None

    # Get owner/repo from the remote
    remote_result = run_gh(["repo", "view", "--json", "owner,name"], check=False)
    if remote_result.returncode != 0:
        return None

    try:
        repo_data = json.loads(remote_result.stdout)
    except json.JSONDecodeError:
        return None

    return PRInfo(
        number=data["number"],
        url=data["url"],
        owner=repo_data["owner"]["login"],
        repo=repo_data["name"],
        head_sha=data.get("headRefOid", ""),
    )


def parse_review_markdown(filepath: str) -> List[Finding]:
    """Parse a review markdown file and extract findings with file paths."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    findings: List[Finding] = []
    current_priority = None

    # Match priority section headers
    priority_pattern = re.compile(r"^##\s+(Critical|High\s*priority|Medium\s*/?\s*good-to-have)", re.IGNORECASE)
    # Match individual finding headers: ### 1. Title
    finding_pattern = re.compile(r"^###\s+(\d+)\.\s+(.+)$", re.MULTILINE)
    # Match file references: **File:** `path/to/file.ext:line`
    file_pattern = re.compile(r"\*\*File:\*\*\s*`([^`]+)`")

    lines = content.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # Check for priority section
        pm = priority_pattern.match(line.strip())
        if pm:
            raw = pm.group(1).strip().lower()
            if "critical" in raw:
                current_priority = "Critical"
            elif "high" in raw:
                current_priority = "High"
            elif "medium" in raw or "good" in raw:
                current_priority = "Medium"
            i += 1
            continue

        # Stop at Positive notes or Summary — those aren't actionable findings
        if re.match(r"^##\s+(Positive\s+notes|Summary)", line.strip(), re.IGNORECASE):
            break

        # Check for finding header
        fm = finding_pattern.match(line.strip())
        if fm and current_priority:
            number = int(fm.group(1))
            title = fm.group(2).strip()

            # Collect the body of this finding until next ### or ## heading
            body_lines = []
            i += 1
            while i < len(lines):
                if re.match(r"^#{2,3}\s+", lines[i].strip()):
                    break
                body_lines.append(lines[i])
                i += 1

            body_text = "\n".join(body_lines).strip()

            # Extract file path and line from body
            file_match = file_pattern.search(body_text)
            file_path = ""
            line_num = None
            if file_match:
                ref = file_match.group(1)
                # Handle multi-file references like "file1:45 and file2:67"
                # Take the first one
                if ":" in ref:
                    parts = ref.rsplit(":", 1)
                    file_path = parts[0].strip()
                    try:
                        line_num = int(parts[1].strip())
                    except ValueError:
                        file_path = ref.strip()
                else:
                    file_path = ref.strip()

            if file_path:
                findings.append(Finding(
                    number=number,
                    title=title,
                    priority=current_priority,
                    file_path=file_path,
                    line=line_num,
                    body=body_text,
                ))
            continue

        i += 1

    return findings


def format_comment_body(finding: Finding, signature: str) -> str:
    """Format a finding into a PR comment body."""
    # Build the comment — include priority tag, the issue body, and signature
    priority_tag = f"**[{finding.priority}]** "
    body = f"{priority_tag}{finding.title}\n\n{finding.body}{signature}"
    return body


def select_findings(findings: List[Finding]) -> List[Finding]:
    """Interactive selection: let user pick which findings to post."""
    print("\n📋 Findings available to post:\n")
    for f in findings:
        line_info = f":{f.line}" if f.line else ""
        print(f"  [{f.number}] [{f.priority}] {f.title}")
        print(f"       {f.file_path}{line_info}")
        print()

    print(f"Total: {len(findings)} findings\n")
    print("Options:")
    print("  all         — Post all findings")
    print("  1,3,5       — Post specific findings by number")
    print("  critical     — Post only Critical findings")
    print("  high         — Post Critical + High findings")
    print("  skip/q       — Cancel, post nothing\n")

    while True:
        try:
            choice = input("Your selection: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nCancelled.")
            return []

        if choice in ("skip", "q", "quit", "cancel"):
            return []
        if choice == "all":
            return findings
        if choice == "critical":
            return [f for f in findings if f.priority == "Critical"]
        if choice == "high":
            return [f for f in findings if f.priority in ("Critical", "High")]

        # Try parsing as comma-separated numbers
        try:
            nums = {int(n.strip()) for n in choice.split(",")}
            selected = [f for f in findings if f.number in nums]
            if selected:
                return selected
            print("No findings matched those numbers. Try again.")
        except ValueError:
            print("Invalid input. Enter 'all', 'critical', 'high', numbers like '1,3,5', or 'skip'.")


def create_pending_review(pr: PRInfo, findings: List[Finding], signature: str) -> bool:
    """Create a PENDING review on the PR with comments via gh api."""
    comments = []
    skipped = []

    for f in findings:
        if not f.file_path:
            skipped.append(f)
            continue

        comment: dict = {
            "path": f.file_path,
            "body": format_comment_body(f, signature),
        }

        # Add line number if available
        if f.line is not None:
            comment["line"] = f.line
            comment["side"] = "RIGHT"  # comment on the new version of the file

        comments.append(comment)

    if not comments:
        print("No comments to post (all findings missing file paths).", file=sys.stderr)
        return False

    if skipped:
        print(f"⚠️  Skipped {len(skipped)} finding(s) without file paths.", file=sys.stderr)

    # Build the review payload
    payload = {
        "event": "PENDING",
        "comments": comments,
    }

    # Use gh api to create the review
    api_path = f"/repos/{pr.owner}/{pr.repo}/pulls/{pr.number}/reviews"

    result = run_gh([
        "api", api_path,
        "--method", "POST",
        "--input", "-",
    ], check=False)

    # Feed the payload via stdin
    result = subprocess.run(
        ["gh", "api", api_path, "--method", "POST", "--input", "-"],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        error_msg = result.stderr.strip()
        # Try to parse the error for a better message
        try:
            err_data = json.loads(result.stdout)
            if "message" in err_data:
                error_msg = err_data["message"]
            if "errors" in err_data:
                for err in err_data["errors"]:
                    error_msg += f"\n  - {err.get('message', err)}"
        except (json.JSONDecodeError, TypeError):
            pass
        print(f"\n❌ Failed to create review: {error_msg}", file=sys.stderr)
        print("\nCommon causes:", file=sys.stderr)
        print("  - File path in review doesn't match the PR diff", file=sys.stderr)
        print("  - Line number is outside the diff hunk", file=sys.stderr)
        print("  - PR is closed or merged", file=sys.stderr)
        print("  - gh CLI not authenticated (run: gh auth login)", file=sys.stderr)
        return False

    # Parse response
    try:
        review_data = json.loads(result.stdout)
        review_id = review_data.get("id", "unknown")
    except json.JSONDecodeError:
        review_id = "unknown"

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Post review findings as pending PR comments via GitHub CLI."
    )
    parser.add_argument(
        "review_file",
        help="Path to the review markdown file (e.g. .review/review-branch.md)"
    )
    parser.add_argument(
        "--pr",
        type=int,
        default=None,
        help="PR number (auto-detected from current branch if omitted)"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        dest="post_all",
        help="Post all findings without interactive selection"
    )
    parser.add_argument(
        "--priority",
        choices=["critical", "high", "medium"],
        default=None,
        help="Only post findings of this priority or higher"
    )
    parser.add_argument(
        "--signature",
        default=None,
        help="Custom signature appended to each comment (overrides default)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be posted without actually creating the review"
    )

    args = parser.parse_args()

    # Validate review file
    if not os.path.isfile(args.review_file):
        print(f"Error: Review file not found: {args.review_file}", file=sys.stderr)
        sys.exit(1)

    # Parse findings
    findings = parse_review_markdown(args.review_file)
    if not findings:
        print("No actionable findings with file paths found in the review.", file=sys.stderr)
        sys.exit(0)

    print(f"📄 Parsed {len(findings)} finding(s) from {args.review_file}")

    # Filter by priority if specified
    if args.priority:
        priority_levels = {
            "critical": ["Critical"],
            "high": ["Critical", "High"],
            "medium": ["Critical", "High", "Medium"],
        }
        allowed = priority_levels[args.priority]
        findings = [f for f in findings if f.priority in allowed]
        if not findings:
            print(f"No findings at priority '{args.priority}' or above.", file=sys.stderr)
            sys.exit(0)
        print(f"🔍 Filtered to {len(findings)} finding(s) at '{args.priority}' priority or above")

    # Detect PR
    pr = detect_pr(args.pr)
    if not pr:
        if args.pr:
            print(f"Error: Could not find PR #{args.pr}. Is 'gh' authenticated?", file=sys.stderr)
        else:
            print("Error: No PR found for current branch.", file=sys.stderr)
            print("Hint: specify --pr <number> or push your branch and open a PR first.", file=sys.stderr)
        sys.exit(1)

    print(f"🔗 PR #{pr.number}: {pr.url}")

    # Confirm PR number with user (unless --all or --dry-run)
    if not args.post_all and not args.dry_run:
        try:
            confirm = input(f"\nPost comments to PR #{pr.number}? [y/N] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nCancelled.")
            sys.exit(0)
        if confirm not in ("y", "yes"):
            print("Cancelled.")
            sys.exit(0)

    # Select findings
    if args.post_all:
        selected = findings
    else:
        selected = select_findings(findings)

    if not selected:
        print("No findings selected. Nothing to post.")
        sys.exit(0)

    # Resolve signature
    signature = args.signature if args.signature else SIGNATURE

    # Dry run — just show what would be posted
    if args.dry_run:
        print(f"\n🏜️  Dry run — would post {len(selected)} comment(s) to PR #{pr.number}:\n")
        for f in selected:
            line_info = f":{f.line}" if f.line else ""
            print(f"  [{f.priority}] {f.title}")
            print(f"    → {f.file_path}{line_info}")
            print()
        return

    # Create the pending review
    print(f"\n📝 Creating pending review with {len(selected)} comment(s)...")
    success = create_pending_review(pr, selected, signature)

    if success:
        files_url = f"{pr.url}/files"
        print(f"\n✅ Pending review created with {len(selected)} comment(s)!")
        print(f"\n👉 Review and submit here: {files_url}")
        print(f"\n   Comments are PENDING — edit or remove any before submitting.")
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
